name: Deploy to Github pages

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github pages
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          site-directory: dist
